apiVersion: v1
kind: Pod
metadata:
  name: tasksapi
spec:
  containers:
    - image: docker.io/jmhal/tasks:1.1
      name: tasks
      ports:
        - containerPort: 10000
          name: http
          protocol: TCP
    - image: docker.io/mongo:latest
      name: mongodb
      ports:
        - containerPort: 27017
          name: socket
          protocol: TCP
